
#   (type: BenchDataset, default: qm9)
dataset: hydronet_medium

# Apply graph packing to the QM9 dataset. (type: bool, default: True)
use_packing: true

# Use synthetic data on the device to disable I/O. (type: bool, default: False)
synthetic_data: false


# CombinedBatch(model_batch_size: int, device_iterations: int = 1, replication_factor: int = 1, gradient_accumulation: int = 1)
combined_batch:

  #   (type: int, default: 16)
  model_batch_size: 7

  #   (type: int, default: 1)
  device_iterations: 4

  #   (type: int, default: 16)
  replication_factor: 16

  #   (type: int, default: 8)
  gradient_accumulation: 32

# The learning rate used by the optimiser. (type: float, default: 0.001)
learning_rate: 0.001

# The number of epochs to benchmark. (type: int, default: 25)
num_epochs: 25

# Run a single training step with profiling enabled and
# saves the profiling report to the provided location. (type: Union[str, null], default: null)
profile_dir:

# the number of tiles used with overlapped IO. (type: Union[int, null], default: 192)
num_io_tiles: 0

# the benchmark task to run. (type: Task, default: train)
task: train

# the random seed to use. (type: int, default: 0)
seed: 0

# the maximum number of data loader workers to use. (type: int, default: 32)
max_workers: 50

# Use Weights and Biases to log benchmark results. (type: bool, default: True)
use_wandb: true
